--
-- PostgreSQL database dump
--

-- Dumped from database version 16.4
-- Dumped by pg_dump version 16.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: product; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.product (
    id bigint NOT NULL,
    active boolean,
    description character varying(255),
    name character varying(255),
    start_date date
);


ALTER TABLE public.product OWNER TO postgres;

--
-- Name: product_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sku; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sku (
    id bigint NOT NULL,
    price double precision,
    sku_code character varying(255),
    product_id bigint
);


ALTER TABLE public.sku OWNER TO postgres;

--
-- Name: sku_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sku ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sku_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: product; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.product (id, active, description, name, start_date) FROM stdin;
1	t	A comfortable cotton t-shirt in black color, size M	T-shirt	2023-05-01
2	t	Slim fit denim jeans in blue color, size S	Jeans	2023-04-15
3	f	Warm and stylish winter jacket in grey color, size L	Jacket	2022-10-20
4	t	Casual sports sneakers in white color, size 42	Sneakers	2023-07-10
5	t	Elegant evening dress in red color, size S	Dress	2023-03-05
6	t	Classic baseball cap in navy color	Cap	2023-08-12
7	f	Woolen winter scarf in green color	Scarf	2022-12-25
8	t	Comfortable summer shorts in khaki color, size M	Shorts	2023-06-20
9	t	Leather belt with buckle in brown color, size L	Belt	2023-09-15
10	t	Cotton crew socks in white color, size M	Socks	2023-07-01
11	t	Cozy cotton hoodie in grey color, size M	Hoodie	2023-02-20
12	t	Leather gloves in black color, size L	Gloves	2023-11-15
13	t	Lightweight blouse in white color, size S	Blouse	2023-03-25
14	t	Casual cotton pants in beige color, size M	Pants	2023-06-05
15	f	Woolen sweater in red color, size XL	Sweater	2023-09-30
16	t	Leather boots in black color, size 43	Boots	2023-10-01
17	t	Formal trousers in navy color, size L	Trousers	2023-07-20
18	t	Formal shirt in light blue color, size M	Shirt	2023-01-15
19	t	Summer straw hat in beige color, size L	Hat	2023-05-10
20	t	Comfortable sandals in brown color, size M	Sandals	2023-04-01
\.


--
-- Data for Name: sku; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.sku (id, price, sku_code, product_id) FROM stdin;
1	19.99	SKU001	1
2	49.99	SKU002	2
3	129.99	SKU003	3
4	69.99	SKU004	4
5	89.99	SKU005	5
6	15.99	SKU006	6
7	25.99	SKU007	7
8	29.99	SKU008	8
9	34.99	SKU009	9
10	12.99	SKU010	10
11	17.99	SKU011	1
12	52.99	SKU012	2
13	119.99	SKU013	3
14	65.99	SKU014	4
15	79.99	SKU015	5
16	14.99	SKU016	6
17	22.99	SKU017	7
18	27.99	SKU018	8
19	32.99	SKU019	9
20	11.99	SKU020	10
21	21.99	SKU021	11
22	59.99	SKU022	12
23	109.99	SKU023	13
24	62.99	SKU024	14
25	85.99	SKU025	15
26	13.99	SKU026	16
27	23.99	SKU027	17
28	26.99	SKU028	18
29	35.99	SKU029	19
30	10.99	SKU030	20
31	18.99	SKU031	1
32	50.99	SKU032	2
33	115.99	SKU033	3
34	67.99	SKU034	4
35	82.99	SKU035	5
36	16.99	SKU036	6
37	24.99	SKU037	7
38	30.99	SKU038	8
39	31.99	SKU039	9
40	13.99	SKU040	10
41	19.99	SKU041	11
42	48.99	SKU042	12
43	130.99	SKU043	13
44	71.99	SKU044	14
45	87.99	SKU045	15
46	14.99	SKU046	16
47	27.99	SKU047	17
48	28.99	SKU048	18
49	35.99	SKU049	19
50	9.99	SKU050	20
\.


--
-- Name: product_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.product_id_seq', 1, false);


--
-- Name: sku_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.sku_id_seq', 1, false);


--
-- Name: product product_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT product_pkey PRIMARY KEY (id);


--
-- Name: sku sku_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sku
    ADD CONSTRAINT sku_pkey PRIMARY KEY (id);


--
-- Name: sku fkovd96qvc9da3k94gf0j822p3o; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sku
    ADD CONSTRAINT fkovd96qvc9da3k94gf0j822p3o FOREIGN KEY (product_id) REFERENCES public.product(id);


--
-- PostgreSQL database dump complete
--

